# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/sm6225-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter tb128fu,$(TARGET_DEVICE)),)

endif
